<?php

namespace App\Entity;

use App\Http\Localization\Localization;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use jeremykenedy\LaravelRoles\Traits\HasRoleAndPermission;

class User extends Authenticatable
{
    use Notifiable;
    use \App\Http\Role\Traits\HasRoleAndPermission;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token'
    ];

    public function setLocale()
    {
        $this->locale = Localization::setLocale();
        return $this->locale;
    }

    public function generateToken()
    {
        $this->api_token = str_random(60);

        return $this->api_token;
    }

    public function toArray()
    {
        return parent::toArray(); // TODO: Change the autogenerated stub
    }
}
